### ISSUE TITLE
[BUG] process.env must contain FRONTEGG_APP_URL even when provided with contextOptions

### ISSUE THREAD

**Issue by bguthrie** [frontegg/frontegg-nextjs#19]
**Describe the bug**

`withFronteggApp` requires that certain config options be provided through `process.env`, even when present in `contextOptions`.

**To Reproduce**

c.f. https://github.com/frontegg/frontegg-nextjs/blob/fe8d71c7ea8827a0381776f2512d45c3fa0d7442/libs/nextjs/src/withFronteggApp.tsx#L40

1. Set up a new NextJS app using `withFronteggApp`.
2. Supply a `contextOptions` object that contains `appUrl`, `baseUrl`, and `clientId`.
3. Receive a runtime exception.

**Expected behavior**

Vercel's env handling is a mess; furthermore, I find it to be good practice to run my env through a runtime type validator and parse any config problems as far in advance of a deploy as process. As a result I generally avoid `process.env`. I'd expect the SDK to be configurable in a variety of ways, and to throw an error only if the data isn't present after attempting to parse it from several sources.

**Comment by rotemzif1** [comment]
hey @bguthrie, this should be handled in our latest version, can you give it a try if you didn't already? Thanks!

**Comment by frontegg-david** [comment]
Hi @bguthrie,
Fix is released with version @frontegg/nextjs v6.7.3. I will resolve the current issue.

You will have to use `FronteggProviderNoSSR` in order to pass baseUrl as props.
The main purpose of using environment variables to setup `FronteggProvider` is give NextJS ServerSide rendering access to these values in order to support getServerSideProps with logged in user's accessToken.

Can you give it a try and let us know if you have any more issues on that.
